### ISSUE TITLE
What happened to EMBOSS-6.6.0 ?

### ISSUE THREAD

**Issue by StuntsPT** [kimrutherford/EMBOSS#1]
The [EMBOSS website](http://emboss.sourceforge.net/news/) states EMBOSS-6.6.0 as the latest version.
I cannot find it anywhere in the FTP server (but I can't seem to find 6.5.7 either).
Is this repository somehow related to upstream?

**Comment by StuntsPT** [comment]
I actually have a local copy of 6.6.0 what was downlaoded at 2014-09-05. Would this be of any help?

**Comment by kimrutherford** [comment]
This is a repository mostly for my own use.  It's definitely not official.  I couldn't see another copy of EMBOSS on GitHub so I imported it.

I have a copy of 6.6.0 but I haven't had a chance to update the repo.  I'll do that later today.

Could you let me know the MD5 checksum of the copy you have?  Thanks!

**Comment by kimrutherford** [comment]
I've import 6.6.0 now.  It looks like the upstream (git://anonscm.debian.org/debian-med/emboss.git) was 6.6.0 with a few Debian fixes.  I probably should have just import 6.6.0 as the first commit.  Oh well, it's v6.6.0 now.

**Comment by StuntsPT** [comment]
Not sure if it's still relevant, but here it is:
md5sum:  cc3fca80cb0618deb10fa0d29fe90e4b
sha256sum: 7184a763d39ad96bb598bfd531628a34aa53e474db9e7cac4416c2a40ab10c6e

**Comment by kimrutherford** [comment]
Thanks, that matches.

**Comment by StuntsPT** [comment]
Thanks for updating to 6.6.0 btw.
