### ISSUE TITLE
How to connect primer 3 with emboss 6.6.0

### ISSUE THREAD

**Issue by aslangabriel** [kimrutherford/EMBOSS#2]
How to connect primer 3 (version 2.4.0 or above) with emboss 6.6.0
Hi，I  tried to relate primer3_core with eprimer3 by creating softlinks under bin folders and export path to emboss_primer3/32_core.  Unfortunately, they didn't work, and always :reported the error that" unable to read sequence; Died: eprimer3/32 terminated: Bad values fpr  sequence and no prompt. My IO platform is ubuntu18.04.
Would you mind fixing it?
Thanks a lot

**Comment by kimrutherford** [comment]
Sorry I'm not the EMBOSS maintainer.  This is just a mirror of the code.
